export type RenderOptions = {
  htmlTemplate?: string;
  id?: string;
  map_id?: string;
  address?: string;
  pic?: string;
  link?: string;
  icon?: string;
  lat?: string;
  lng?: string;
  anim?: string;
  title?: string;
  infoopen?: string;
  category?: string;
  approved?: string;
  retina?: string;
  type?: string;
  did?: string;
  other_data?: string;
  sticky?: string;
};
